micronaut:
  application:
    name: ec-szperacz
  server:
    cors:
      enabled: true

redis:
  uri: redis://10.10.38.81:6379

logger:
  levels:
    io.lettuce.core: ERROR

szperacz:
  event-fetch-limit: 25000
  kafka:
    group-id: szperacz
    bootstrap-servers: 10.10.38.201:6667
  catalog:
    path: '/szperacz_catalog/'
    compress-files: false
